steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --no-cache
      - -t
      - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - -f
      - Dockerfile

  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA

  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - --platform=managed
      - --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - --region=$_DEPLOY_REGION
      - --memory=2Gi
      - --cpu=2
      - --concurrency=10
      - --min-instances=0
      - --max-instances=10
      - --timeout=900s
      - --quiet

images:
  - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE

substitutions:
  _AR_HOSTNAME: asia-southeast1-docker.pkg.dev
  _AR_PROJECT_ID: gen-lang-client-0550650014
  _AR_REPOSITORY: cloud-run-source-deploy
  _DEPLOY_REGION: asia-southeast1
  _PLATFORM: managed
  _SERVICE_NAME: kreasi-ai

tags:
  - gcp-cloud-build-deploy-cloud-run
  - kreasi-ai
